// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJr-d_Jp1g0YMJewGhxumhwL4EUmDJ74g',
    appId: '1:368344569775:web:020724f9023e3ca341015a',
    messagingSenderId: '368344569775',
    projectId: 'mobile-f453c',
    authDomain: 'mobile-f453c.firebaseapp.com',
    databaseURL: 'https://mobile-f453c-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-f453c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMjuZvGMVlOB038pSQGuXDz668M_YQRlw',
    appId: '1:368344569775:android:0f18baa8ed1bbe1441015a',
    messagingSenderId: '368344569775',
    projectId: 'mobile-f453c',
    databaseURL: 'https://mobile-f453c-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-f453c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGqaNkX-SE3GJ4Le04XH5FXGrnNuD555g',
    appId: '1:368344569775:ios:19042038a96d654341015a',
    messagingSenderId: '368344569775',
    projectId: 'mobile-f453c',
    databaseURL: 'https://mobile-f453c-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-f453c.appspot.com',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGqaNkX-SE3GJ4Le04XH5FXGrnNuD555g',
    appId: '1:368344569775:ios:f76c47213c080f6041015a',
    messagingSenderId: '368344569775',
    projectId: 'mobile-f453c',
    databaseURL: 'https://mobile-f453c-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-f453c.appspot.com',
    iosBundleId: 'com.example.mobileAppProject.RunnerTests',
  );
}
